spring:
  config:
    import: optional:file:.env[.properties]

server:
  port: 8083

http:
  base:
    url: ${DEAL_HOST}
  endpoints:
    createOffers: "/deal/statement"
    selectOffer: "/deal/offer/select"
