server:
  port: 8085

http:
  urls:
    calculator: ${CALCULATOR_HOST}
    deal: ${DEAL_HOST}
    statement: ${STATEMENT_HOST}
  endpoints:
    calculator:
      calculatorOffers: "/calculator/offers"
      calculatorCalc: "/calculator/calc"
    statement:
      statement: "/statement"
      statementOffer: "/statement/offer"
    deal:
      dealStatement: " /deal/statement"
      dealOfferSelect: " /deal/offer/select"
      dealCalculate: " /deal/calculate"
      dealDocument: " /deal/document"
      dealAdminStatement: "/deal/admin/statement"
