server:
  port: 8085

http:
  urls:
    calculator: ${CALCULATOR_HOST:http://localhost:8081}
    deal: ${DEAL_HOST:http://localhost:8082}
    statement: ${STATEMENT_HOST:http://localhost:8083}
  endpoints:
    calculator:
      calculatorOffers: "/calculator/offers"
      calculatorCalc: "/calculator/calc"
    statement:
      statement: "/statement"
      statementOffer: "/statement/offer"
    deal:
      dealStatement: " /deal/statement"
      dealOfferSelect: " /deal/offer/select"
      dealCalculate: " /deal/calculate"
      dealDocument: " /deal/document"
      dealAdminStatement: "/deal/admin/statement"


management:
  metrics:
    tags:
      application: gateway
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    dev.davletshin.gateway: INFO
    org.springframework: INFO
