spring:
  application:
    name: calculator

server:
  port: 8081

credit:
  info:
    defaultRate: 13

management:
  metrics:
    tags:
      application: calculator
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    dev.davletshin.calculator: INFO
    org.springframework: INFO


