server:
  port: 8084

spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: json
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: dev.davletshin.dossier.dto.EmailMessageDTO
        spring.json.use.type.headers: false
      auto-offset-reset: earliest
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

kafka:
  topics: finish-registration, create-documents, send-documents, send_ses, credit-issued, statement-denied
  group-id: json

management:
  metrics:
    tags:
      application: dossier
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    dev.davletshin.dossier: INFO
    org.springframework: INFO

http:
  urls:
    deal: ${DEAL_HOST:http://localhost:8082}
    endpoint: "/deal/admin/statement"
