name: maven-build
on:
  push:
    branches: [ "*" ]

jobs:
  maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: |
          mvn clean install

  publish-snapshot:
    needs: maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Publish SNAPSHOT version to GitHub Packages (we can skip tests since we only deploy if the build workflow succeeded)
        run: mvn -B --no-transfer-progress deploy -DskipTests --projects bankingapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}